### PR TITLE
Fix of comments timestamp styles. Closes #620.

### LINKED ISSUE #620: Fix comments and side-comments timestamp labels styles
- [x] Separate the timestamp from the user's name a bit more (this was actually fixed in #515 but I'm not quite sure how we got that bug back in).
- [x] remove the trailing `:` from the timestamp label

Related to #619

### PR DESCRIPTION
**Pull request by jfresco**

### CODE REVIEW

File: lib/boot/boot.js [hunk 1]
```diff
@@ -64,6 +64,10 @@ bus.on('commentadded', function() {
   timestamps.update();
 });
 
+bus.on('comments-replies:loaded', function() {
+  timestamps.update();
+});
+
```
Comment (gvilarino) [inline lib/boot/boot.js]: It isn't right to put these kind of event handling in `boot/boot.js`; this should be handled elsewhere.

Comment (jfresco) [inline lib/boot/boot.js]: Have to be handled in the scope of `timestamps`.
What do you suggest to do? Can you provide an example of a similar case?

Comment (gvilarino) [inline lib/boot/boot.js]: This can be done in many ways; what needs to be clear is that this one is in direct contradiction with #284 and thus the architecture we've chosen for the frontend.

One sensible approach would be wrapping `timeago` with a local component (singleton maybe?) that either self-configures or lets its clients subscribe to its events (extend `Emitter`); sort it out from there I think.

**Comment by gvilarino** [comment]
I'm merging this because it's a perceivable fix, but I'm opening a new issue in order to refactor the whole approach.

**Comment by gvilarino** [comment]
Continue this discussion in #631

/thread
